spring.application.name=acomp_tour


spring.datasource.url=jdbc:mysql://localhost:3306/gerenciamento_restaurantes
spring.datasource.username=root
spring.datasource.password= Senha
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mvc.hiddenmethod.filter.enabled=true